# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07ee6ee8c14a0562ec52d78da48f66baf891d22b92454e5b9cf2587baae06a547b2699f392c689bd3dcb83fcc8477bf8257ded757f68106d95a0b8b9020303bd

test:
  secret_key_base: 31be8afc8a06d502dff1fe3871765f3bcaa6ec6fbcd18e81ce3981ad92418c254bdc5ddf1c1834718ffe189a6f8932d2cce135c8c8ddd27b8d4a44e25aa07637

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
